### ISSUE TITLE
Saved custom perspectives disappear

### ISSUE THREAD

**Issue by hack-r** [Bio7/bio7#2]
Anytime I close and later reopen Bio7 my saved custom perspectives are gone. Is this a bug?

Could it be to do with the clearPersistedState default option in the configuration file?

**Comment by Bio7** [comment]
This is a general bug in Eclipse since 4.0 due to the API changes and the will to improve Eclipse in general. Until Eclipse 4.4 as basis of Bio7 the Eclipse platform was not usable.

The -clearPersistedState was introduced because without some strange GUI behaviour appeared. Of course you can test it yourself.

I heard that this feature will be functional with Eclipse 4.6

As a workaround for custom GUI's I introduced a default Custom perspective which can be filled with views (using a script) dynamically. The disadvantage is that you can't positioned existing views exactly but custom views can. Eventually custom views can be used as a placeholder in the Custom perspective.

See: http://bio7.org/manual/Main.html#toc-Section-4.9

A call to the custom elements can be wrapped easily in a script and then extend the main menu of Bio7.

Here are some older flash tutorials:

http://www.uni-bielefeld.de/biologie/Oekosystembiologie/bio7app/flashtut/custompersp.htm
http://www.uni-bielefeld.de/biologie/Oekosystembiologie/bio7app/flashtut/createscript.htm


Example:

Work.openPerspective("com.eco.bio7.CustomPerspective");
//Available Bio7 views can not positioned but Custom views can!

Work.openView("org.eclipse.ui.console.ConsoleView");
CustomView view=new CustomView();
Composite parent = view.getComposite("left");
Display dis = CustomView.getDisplay();
...............................................
..............................
/*
Possible custom view id's (default perspective locations) are:

left
right
subLeftTop
subLeftBottom
subRightTop
subRightBottom
subRightBottomLeft
subRightBottomRight
subRightBottomLeftTop
subRightBottomLeftBottom
*/
Examples for custom views can be here:

https://github.com/Bio7/bio7_examples/tree/master/Bio7_Script_Examples/Bio7_GUI_Snippets/Bio7-Custom
Or for JavaFX here:
https://github.com/Bio7/bio7_examples/tree/master/Bio7_Java_Examples/src/javafx

**Comment by Bio7** [comment]
See also:

http://blog.vogella.com/2010/10/17/saveandrestore-e4/

**Comment by hack-r** [comment]
Thank you very much!
